FORMAT: 1A
HOST: http://www.google.com

# ICGMMocks
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Global Regions [/regions]
### List all Notes [GET]
+ Response 200 (application/json)

        [
            {
                "identifier" : 1,
                "name" : "EMEA",
                "requests" : 1200,
                "location" : {"lat" : 48.122632, "long" : 14.604547},
            "subregions":
            [
                {
                    "identifier" : 101,
                    "name" : "Algeria",
                },
                {
                    "identifier" : 102,
                    "name" : "Austria",
                },
                {
                    "identifier" : 103,
                    "name" : "Bahrain",
                },
                {
                    "identifier" : 104,
                    "name" : "Belgium",
                },
                {
                    "identifier" : 105,
                    "name" : "Bulgaria",
                },
                {
                    "identifier" : 106,
                    "name" : "Cameroon",
                },
                {
                    "identifier" : 107,
                    "name" : "Congo",
                },
                {
                    "identifier" : 108,
                    "name" : "Czech Republic",
                },
                {
                    "identifier" : 109,
                    "name" : "Denmark",
                },
                {
                    "identifier" : 110,
                    "name" : "Egypt",
                },
                {
                    "identifier" : 111,
                    "name" : "Finland",
                },
                {
                    "identifier" : 112,
                    "name" : "France",
                },
                {
                    "identifier" : 113,
                    "name" : "Gabon",
                },
                {
                    "identifier" : 114,
                    "name" : "Germany",
                },
                {
                    "identifier" : 115,
                    "name" : "Greece",
                },
                {
                    "identifier" : 116,
                    "name" : "Ireland",
                },
                {
                    "identifier" : 117,
                    "name" : "Israel",
                },
                {
                    "identifier" : 118,
                    "name" : "Italy",
                },
                {
                    "identifier" : 119,
                    "name" : "Ivory Coast",
                },
                {
                    "identifier" : 120,
                    "name" : "Jersey C.I.",
                },
                {
                    "identifier" : 121,
                    "name" : "Jordan",
                },
                {
                    "identifier" : 122,
                    "name" : "Kazakhstan",
                },
                {
                    "identifier" : 123,
                    "name" : "Kenya",
                },
                {
                    "identifier" : 124,
                    "name" : "Kuwait",
                },
                {
                    "identifier" : 125,
                    "name" : "Lebanon",
                },
                {
                    "identifier" : 126,
                    "name" : "Luxembourg",
                },
                {
                    "identifier" : 127,
                    "name" : "Morocco",
                },
                {
                    "identifier" : 128,
                    "name" : "Netherlands",
                },
                {
                    "identifier" : 129,
                    "name" : "Nigeria",
                },
                {
                    "identifier" : 130,
                    "name" : "Norway",
                },
                {
                    "identifier" : 131,
                    "name" : "Pakistan",
                },
                {
                    "identifier" : 132,
                    "name" : "Poland",
                },
                {
                    "identifier" : 133,
                    "name" : "Portugal",
                },
                {
                    "identifier" : 134,
                    "name" : "Qatar",
                },
                {
                    "identifier" : 135,
                    "name" : "Romania",
                },
                {
                    "identifier" : 136,
                    "name" : "Russia",
                },
                {
                    "identifier" : 137,
                    "name" : "Senegal",
                },
                {
                    "identifier" : 139,
                    "name" : "Slovakia",
                },
                {
                    "identifier" : 140,
                    "name" : "South Africa",
                },
                {
                    "identifier" : 138,
                    "name" : "Spain",
                },
                {
                    "identifier" : 141,
                    "name" : "Sweden",
                },
                {
                    "identifier" : 142,
                    "name" : "Switzerland",
                },
                {
                    "identifier" : 143,
                    "name" : "Tanzania",
                },
                {
                    "identifier" : 144,
                    "name" : "Tunisia",
                },
                {
                    "identifier" : 145,
                    "name" : "Turkey",
                },
                {
                    "identifier" : 148,
                    "name" : "UAE",
                },
                {
                    "identifier" : 146,
                    "name" : "Uganda",
                },
                {
                    "identifier" : 147,
                    "name" : "Ukraine",
                },
                {
                    "identifier" : 149,
                    "name" : "United Kingdom",
                },
            ]
            
            },
            {
                "identifier" : 2,
                "name" : "NAM",
                "requests" : 800,
                "location" : {"lat" : 50.000000, "long" : -98.575328},
                "subregions": 
                [
                    {
                        "identifier": 201,
                        "name": "USA"
                    },
                    {
                        "identifier": 202,
                        "name": "Canada"
                    },
                ]                
            },
            {
                "identifier" : 3,
                "name" : "LATAM",
                "requests" : 150,
                "location" : {"lat" : 3.501314, "long" : -72.872505},
                            "subregions":
            [
                {
                    "identifier" : 301,
                    "name" : "Argentina",
                },
                {
                    "identifier" : 302,
                    "name" : "Bahamas",
                },
                {
                    "identifier" : 303,
                    "name" : "Barbados",
                },
                {
                    "identifier" : 304,
                    "name" : "Brazil",
                },
                {
                    "identifier" : 305,
                    "name" : "Chile",
                },
                {
                    "identifier" : 306,
                    "name" : "Colombia",
                },
                {
                    "identifier" : 307,
                    "name" : "Costa Rica",
                },
                {
                    "identifier" : 308,
                    "name" : "Dominican Republic",
                },
                {
                    "identifier" : 309,
                    "name" : "Ecuador",
                },
                {
                    "identifier" : 310,
                    "name" : "El Salvador",
                },
                {
                    "identifier" : 311,
                    "name" : "Guatemala",
                },
                {
                    "identifier" : 312,
                    "name" : "Haiti",
                },
                {
                    "identifier" : 313,
                    "name" : "Honduras",
                },
                {
                    "identifier" : 314,
                    "name" : "Jamaica",
                },
                {
                    "identifier" : 315,
                    "name" : "Mexico",
                },
                {
                    "identifier" : 316,
                    "name" : "Nicaragua",
                },
                {
                    "identifier" : 317,
                    "name" : "Panama",
                },
                {
                    "identifier" : 318,
                    "name" : "Paraguay",
                },
                {
                    "identifier" : 319,
                    "name" : "Peru",
                },
                {
                    "identifier" : 320,
                    "name" : "Puerto Rico",
                },
                {
                    "identifier" : 321,
                    "name" : "Trinidad & Tobago",
                },
                {
                    "identifier" : 323,
                    "name" : "Uruguay",
                },
                {
                    "identifier" : 322,
                    "name" : "Venezuela",
                },

           ]

            },
            {
                "identifier" : 4,
                "name" : "ASIA",
                "requests" : 400,
                "location" : {"lat" : 22.358535, "long" : 114.142271},
            "subregions":
            [
                {
                    "identifier" : 401,
                    "name" : "Australia",
                },
                {
                    "identifier" : 402,
                    "name" : "Bangladesh",
                },
                {
                    "identifier" : 404,
                    "name" : "China",
                },
                {
                    "identifier" : 405,
                    "name" : "Hong Kong",
                },
                {
                    "identifier" : 406,
                    "name" : "India",
                },
                {
                    "identifier" : 407,
                    "name" : "Indonesia",
                },
                {
                    "identifier" : 408,
                    "name" : "Japan",
                },
                {
                    "identifier" : 403,
                    "name" : "Macau",
                },
                {
                    "identifier" : 409,
                    "name" : "Malaysia",
                },
                {
                    "identifier" : 410,
                    "name" : "New Zealand",
                },
                {
                    "identifier" : 411,
                    "name" : "Philippines",
                },
                {
                    "identifier" : 412,
                    "name" : "Singapore",
                },
                {
                    "identifier" : 413,
                    "name" : "South Korea",
                },
                {
                    "identifier" : 414,
                    "name" : "Sri Lanka",
                },
                {
                    "identifier" : 415,
                    "name" : "Taiwan",
                },
                {
                    "identifier" : 416,
                    "name" : "Thailand",
                },
                {
                    "identifier" : 417,
                    "name" : "Vietnam",
                },
                {
                    "identifier" : 401,
                    "name" : "Australia",
                },
                {
                    "identifier" : 402,
                    "name" : "Bangladesh",
                },
                {
                    "identifier" : 404,
                    "name" : "China",
                },
                {
                    "identifier" : 405,
                    "name" : "Hong Kong",
                },
                {
                    "identifier" : 406,
                    "name" : "India",
                },
                {
                    "identifier" : 407,
                    "name" : "Indonesia",
                },
                {
                    "identifier" : 408,
                    "name" : "Japan",
                },
                {
                    "identifier" : 403,
                    "name" : "Macau",
                },
                {
                    "identifier" : 409,
                    "name" : "Malaysia",
                },
                {
                    "identifier" : 410,
                    "name" : "New Zealand",
                },
                {
                    "identifier" : 411,
                    "name" : "Philippines",
                },
                {
                    "identifier" : 412,
                    "name" : "Singapore",
                },
                {
                    "identifier" : 413,
                    "name" : "South Korea",
                },
                {
                    "identifier" : 414,
                    "name" : "Sri Lanka",
                },
                {
                    "identifier" : 415,
                    "name" : "Taiwan",
                },
                {
                    "identifier" : 416,
                    "name" : "Thailand",
                },
                {
                    "identifier" : 417,
                    "name" : "Vietnam",
                },
           ]
            }
        ]

## EMEA [/regions/1]
EMEA region

### Retrieve a EMEA [GET]
+ Response 200 (application/json)

        [
          {
            "identifier": 1,
            "subregions":
            [
                {
                    "identifier" : 101,
                    "name" : "Algeria",
                    "requests" : 216,
                    "location" : {"lat" : 27.972528, "long" : 1.680449}
                },
                {
                    "identifier" : 102,
                    "name" : "Austria",
                    "requests" : 60,
                    "location" : {"lat" : 47.648006, "long" : 14.844832}
                },
                {
                    "identifier" : 103,
                    "name" : "Bahrain",
                    "requests" : 117,
                    "location" : {"lat" : 25.995459, "long" : 50.588295}
                },
                {
                    "identifier" : 104,
                    "name" : "Belgium",
                    "requests" : 67,
                    "location" : {"lat" : 50.615334, "long" : 4.524691}
                },
                {
                    "identifier" : 105,
                    "name" : "Bulgaria",
                    "requests" : 101,
                    "location" : {"lat" : 42.676997, "long" : 25.429783}
                },
                {
                    "identifier" : 106,
                    "name" : "Cameroon",
                    "requests" : 177,
                    "location" : {"lat" : 4.717083, "long" : 11.747020}
                },
                {
                    "identifier" : 107,
                    "name" : "Congo",
                    "requests" : 56,
                    "location" : {"lat" : -0.229490, "long" : 15.935776}
                },
                {
                    "identifier" : 108,
                    "name" : "Czech Republic",
                    "requests" : 88,
                    "location" : {"lat" : 49.739148, "long" : 15.334474}
                },
                {
                    "identifier" : 109,
                    "name" : "Denmark",
                    "requests" : 114,
                    "location" : {"lat" : 55.959795, "long" : 10.077215}
                },
                {
                    "identifier" : 110,
                    "name" : "Egypt",
                    "requests" : 63,
                    "location" : {"lat" : 25.984796, "long" : 29.406176}
                },
                {
                    "identifier" : 111,
                    "name" : "Finland",
                    "requests" : 3,
                    "location" : {"lat" : 64.010864, "long" : 26.627660}
                },
                {
                    "identifier" : 112,
                    "name" : "France",
                    "requests" : 93,
                    "location" : {"lat" : 46.648713, "long" : 2.621566}
                },
                {
                    "identifier" : 113,
                    "name" : "Gabon",
                    "requests" : 49,
                    "location" : {"lat" : -1.343877, "long" : 11.721494}
                },
                {
                    "identifier" : 114,
                    "name" : "Germany",
                    "requests" : 190,
                    "location" : {"lat" : 50.627542, "long" : 9.958450}
                },
                {
                    "identifier" : 115,
                    "name" : "Greece",
                    "requests" : 205,
                    "location" : {"lat" : 39.069507, "long" : 22.034456}
                },
                {
                    "identifier" : 116,
                    "name" : "Ireland",
                    "requests" : 83,
                    "location" : {"lat" : 53.075668, "long" : -7.836500}
                },
                {
                    "identifier" : 117,
                    "name" : "Israel",
                    "requests" : 224,
                    "location" : {"lat" : 31.467059, "long" : 34.814643}
                },
                {
                    "identifier" : 118,
                    "name" : "Italy",
                    "requests" : 232,
                    "location" : {"lat" : 42.763190, "long" : 12.251522}
                },
                {
                    "identifier" : 119,
                    "name" : "Ivory Coast",
                    "requests" : 98,
                    "location" : {"lat" : 7.547363, "long" : -5.566505}
                },
                {
                    "identifier" : 120,
                    "name" : "Jersey C.I.",
                    "requests" : 94,
                    "location" : {"lat" : 49.214379, "long" : -2.132660}
                },
                {
                    "identifier" : 121,
                    "name" : "Jordan",
                    "requests" : 134,
                    "location" : {"lat" : 31.125730, "long" : 36.392121}
                },
                {
                    "identifier" : 122,
                    "name" : "Kazakhstan",
                    "requests" : 47,
                    "location" : {"lat" : 47.827276, "long" : 67.382857}
                },
                {
                    "identifier" : 123,
                    "name" : "Kenya",
                    "requests" : 21,
                    "location" : {"lat" : 0.500765, "long" : 37.609136}
                },
                {
                    "identifier" : 124,
                    "name" : "Kuwait",
                    "requests" : 97,
                    "location" : {"lat" : 29.360775, "long" : 47.633579}
                },
                {
                    "identifier" : 125,
                    "name" : "Lebanon",
                    "requests" : 186,
                    "location" : {"lat" : 34.191738, "long" : 35.887572}
                },
                {
                    "identifier" : 126,
                    "name" : "Luxembourg",
                    "requests" : 61,
                    "location" : {"lat" : 49.777585, "long" : 6.094806}
                },
                {
                    "identifier" : 127,
                    "name" : "Morocco",
                    "requests" : 98,
                    "location" : {"lat" : 31.713478, "long" : -6.483976}
                },
                {
                    "identifier" : 128,
                    "name" : "Netherlands",
                    "requests" : 196,
                    "location" : {"lat" : 52.730774, "long" : 5.835204}
                },
                {
                    "identifier" : 129,
                    "name" : "Nigeria",
                    "requests" : 237,
                    "location" : {"lat" : 9.553236, "long" : 8.074850}
                },
                {
                    "identifier" : 130,
                    "name" : "Norway",
                    "requests" : 60,
                    "location" : {"lat" : 61.457979, "long" : 8.971401}
                },
                {
                    "identifier" : 131,
                    "name" : "Pakistan",
                    "requests" : 242,
                    "location" : {"lat" : 29.878937, "long" : 69.913918}
                },
                {
                    "identifier" : 132,
                    "name" : "Poland",
                    "requests" : 56,
                    "location" : {"lat" : 52.129535, "long" : 19.394454}
                },
                {
                    "identifier" : 133,
                    "name" : "Portugal",
                    "requests" : 223,
                    "location" : {"lat" : 39.658470, "long" : -8.244460}
                },
                {
                    "identifier" : 134,
                    "name" : "Qatar",
                    "requests" : 40,
                    "location" : {"lat" : 25.525388, "long" : 51.217536}
                },
                {
                    "identifier" : 135,
                    "name" : "Romania",
                    "requests" : 124,
                    "location" : {"lat" : 45.780363, "long" : 24.990706}
                },
                {
                    "identifier" : 136,
                    "name" : "Russia",
                    "requests" : 57,
                    "location" : {"lat" : 61.987429, "long" : 96.714855}
                },
                {
                    "identifier" : 137,
                    "name" : "Senegal",
                    "requests" : 87,
                    "location" : {"lat" : 14.502785, "long" : -14.654668}
                },
                {
                    "identifier" : 139,
                    "name" : "Slovakia",
                    "requests" : 217,
                    "location" : {"lat" : 48.706566, "long" : 19.487012}
                },
                {
                    "identifier" : 140,
                    "name" : "South Africa",
                    "requests" : 84,
                    "location" : {"lat" : -29.140993, "long" : 24.367460}
                },
                {
                    "identifier" : 138,
                    "name" : "Spain",
                    "requests" : 31,
                    "location" : {"lat" : 41.270000, "long" : -3.210000}
                },
                {
                    "identifier" : 141,
                    "name" : "Sweden",
                    "requests" : 95,
                    "location" : {"lat" : 62.736314, "long" : 15.365470}
                },
                {
                    "identifier" : 142,
                    "name" : "Switzerland",
                    "requests" : 88,
                    "location" : {"lat" : 46.715779, "long" : 8.402655}
                },
                {
                    "identifier" : 143,
                    "name" : "Tanzania",
                    "requests" : 18,
                    "location" : {"lat" : -6.453096, "long" : 34.894539}
                },
                {
                    "identifier" : 144,
                    "name" : "Tunisia",
                    "requests" : 146,
                    "location" : {"lat" : 34.207649, "long" : 9.465427}
                },
                {
                    "identifier" : 145,
                    "name" : "Turkey",
                    "requests" : 173,
                    "location" : {"lat" : 39.061415, "long" : 35.124582}
                },
                {
                    "identifier" : 148,
                    "name" : "UAE",
                    "requests" : 111,
                    "location" : {"lat" : 24.091352, "long" : 54.123035}
                },
                {
                    "identifier" : 146,
                    "name" : "Uganda",
                    "requests" : 0,
                    "location" : {"lat" : 1.105402, "long" : 32.520620}
                },
                {
                    "identifier" : 147,
                    "name" : "Ukraine",
                    "requests" : 110,
                    "location" : {"lat" : 49.395662, "long" : 30.980984}
                },
                {
                    "identifier" : 149,
                    "name" : "United Kingdom",
                    "requests" : 240,
                    "location" : {"lat" : 54.260582, "long" : -1.979057}
                },
            ]
          }
        ]

## NAM [/regions/2]
NAM region

### Retrieve a NAM [GET]
+ Response 200 (application/json)

        [
          {
            "identifier": 2,
            "subregions": [
              {
                "identifier": 201,
                "requests" : 1000,
                "name": "USA"
              },
              {
                "identifier": 202,
                "requests" : 800,
                "name": "Canada"
              },
            ]
          }
        ]

## LATAM [/regions/3]
LATAM region

### Retrieve a LATAM [GET]
+ Response 200 (application/json)

        [
          {
            "identifier": 3,
            "subregions":
            [
                {
                    "identifier" : 301,
                    "name" : "Argentina",
                    "requests" : 75,
                    "location" : {"lat" : -37.157467, "long" : -64.316465}
                },
                {
                    "identifier" : 302,
                    "name" : "Bahamas",
                    "requests" : 66,
                    "location" : {"lat" : 25.000000, "long" : -77.400000}
                },
                {
                    "identifier" : 303,
                    "name" : "Barbados",
                    "requests" : 90,
                    "location" : {"lat" : 13.169025, "long" : -59.555144}
                },
                {
                    "identifier" : 304,
                    "name" : "Brazil",
                    "requests" : 24,
                    "location" : {"lat" : -9.683468, "long" : -52.308555}
                },
                {
                    "identifier" : 305,
                    "name" : "Chile",
                    "requests" : 178,
                    "location" : {"lat" : -34.572976, "long" : -71.095732}
                },
                {
                    "identifier" : 306,
                    "name" : "Colombia",
                    "requests" : 35,
                    "location" : {"lat" : 3.501314, "long" : -72.872505}
                },
                {
                    "identifier" : 307,
                    "name" : "Costa Rica",
                    "requests" : 214,
                    "location" : {"lat" : 9.845554, "long" : -83.862439}
                },
                {
                    "identifier" : 308,
                    "name" : "Dominican Republic",
                    "requests" : 87,
                    "location" : {"lat" : 18.892313, "long" : -70.206847}
                },
                {
                    "identifier" : 309,
                    "name" : "Ecuador",
                    "requests" : 240,
                    "location" : {"lat" : -1.519327, "long" : -78.356744}
                },
                {
                    "identifier" : 310,
                    "name" : "El Salvador",
                    "requests" : 229,
                    "location" : {"lat" : 13.631710, "long" : -88.910934}
                },
                {
                    "identifier" : 311,
                    "name" : "Guatemala",
                    "requests" : 74,
                    "location" : {"lat" : 15.609342, "long" : -90.560028}
                },
                {
                    "identifier" : 312,
                    "name" : "Haiti",
                    "requests" : 213,
                    "location" : {"lat" : 20.000000, "long" : -73.000000}
                },
                {
                    "identifier" : 313,
                    "name" : "Honduras",
                    "requests" : 151,
                    "location" : {"lat" : 14.504704, "long" : -87.225643}
                },
                {
                    "identifier" : 314,
                    "name" : "Jamaica",
                    "requests" : 61,
                    "location" : {"lat" : 18.115368, "long" : -77.160905}
                },
                {
                    "identifier" : 315,
                    "name" : "Mexico",
                    "requests" : 127,
                    "location" : {"lat" : 22.406570, "long" : -101.844884}
                },
                {
                    "identifier" : 316,
                    "name" : "Nicaragua",
                    "requests" : 99,
                    "location" : {"lat" : 12.139432, "long" : -84.908726}
                },
                {
                    "identifier" : 317,
                    "name" : "Panama",
                    "requests" : 236,
                    "location" : {"lat" : 8.641033, "long" : -80.405860}
                },
                {
                    "identifier" : 318,
                    "name" : "Paraguay",
                    "requests" : 23,
                    "location" : {"lat" : -23.487637, "long" : -58.305235}
                },
                {
                    "identifier" : 319,
                    "name" : "Peru",
                    "requests" : 53,
                    "location" : {"lat" : -9.788561, "long" : -75.516214}
                },
                {
                    "identifier" : 320,
                    "name" : "Puerto Rico",
                    "requests" : 147,
                    "location" : {"lat" : 18.215691, "long" : -66.414655}
                },
                {
                    "identifier" : 321,
                    "name" : "Trinidad & Tobago",
                    "requests" : 15,
                    "location" : {"lat" : 10.485968, "long" : -61.255908}
                },
                {
                    "identifier" : 323,
                    "name" : "Uruguay",
                    "requests" : 30,
                    "location" : {"lat" : -33.121092, "long" : -55.900528}
                },
                {
                    "identifier" : 322,
                    "name" : "Venezuela",
                    "requests" : 157,
                    "location" : {"lat" : 7.076774, "long" : -66.091605}
                },

           ]
          }
        ]

## ASIA [/regions/4]
ASIA region

### Retrieve a ASIA [GET]
+ Response 200 (application/json)

        [
          {
            "identifier": 4,
            "subregions":
            [
                {
                    "identifier" : 401,
                    "name" : "Australia",
                    "requests" : 237,
                    "location" : {"lat" : -25.047944, "long" : 134.003347}
                },
                {
                    "identifier" : 402,
                    "name" : "Bangladesh",
                    "requests" : 127,
                    "location" : {"lat" : 23.795572, "long" : 90.283221}
                },
                {
                    "identifier" : 404,
                    "name" : "China",
                    "requests" : 8,
                    "location" : {"lat" : 34.740765, "long" : 101.319735}
                },
                {
                    "identifier" : 405,
                    "name" : "Hong Kong",
                    "requests" : 77,
                    "location" : {"lat" : 23.500000, "long" : 114.500000}
                },
                {
                    "identifier" : 406,
                    "name" : "India",
                    "requests" : 244,
                    "location" : {"lat" : 23.041173, "long" : 78.891805}
                },
                {
                    "identifier" : 407,
                    "name" : "Indonesia",
                    "requests" : 80,
                    "location" : {"lat" : -3.187229, "long" : 119.851232}
                },
                {
                    "identifier" : 408,
                    "name" : "Japan",
                    "requests" : 90,
                    "location" : {"lat" : 38.280000, "long" : 140.460000}
                },
                {
                    "identifier" : 403,
                    "name" : "Macau",
                    "requests" : 73,
                    "location" : {"lat" : 22.000000, "long" : 113.000000}
                },
                {
                    "identifier" : 409,
                    "name" : "Malaysia",
                    "requests" : 1,
                    "location" : {"lat" : 3.988639, "long" : 102.064055}
                },
                {
                    "identifier" : 410,
                    "name" : "New Zealand",
                    "requests" : 39,
                    "location" : {"lat" : -45.000000, "long" : 168.000000}
                },
                {
                    "identifier" : 411,
                    "name" : "Philippines",
                    "requests" : 21,
                    "location" : {"lat" : 12.415512, "long" : 123.431038}
                },
                {
                    "identifier" : 412,
                    "name" : "Singapore",
                    "requests" : 112,
                    "location" : {"lat" : 1.356203, "long" : 103.828142}
                },
                {
                    "identifier" : 413,
                    "name" : "South Korea",
                    "requests" : 228,
                    "location" : {"lat" : 36.458351, "long" : 127.855841}
                },
                {
                    "identifier" : 414,
                    "name" : "Sri Lanka",
                    "requests" : 49,
                    "location" : {"lat" : 7.517242, "long" : 80.779494}
                },
                {
                    "identifier" : 415,
                    "name" : "Taiwan",
                    "requests" : 164,
                    "location" : {"lat" : 23.752054, "long" : 120.927318}
                },
                {
                    "identifier" : 416,
                    "name" : "Thailand",
                    "requests" : 222,
                    "location" : {"lat" : 15.660392, "long" : 101.520053}
                },
                {
                    "identifier" : 417,
                    "name" : "Vietnam",
                    "requests" : 214,
                    "location" : {"lat" : 13.318655, "long" : 108.368100}
                },
                {
                    "identifier" : 401,
                    "name" : "Australia",
                    "requests" : 237,
                    "location" : {"lat" : -25.047944, "long" : 134.003347}
                },
                {
                    "identifier" : 402,
                    "name" : "Bangladesh",
                    "requests" : 127,
                    "location" : {"lat" : 23.795572, "long" : 90.283221}
                },
                {
                    "identifier" : 404,
                    "name" : "China",
                    "requests" : 8,
                    "location" : {"lat" : 34.740765, "long" : 101.319735}
                },
                {
                    "identifier" : 405,
                    "name" : "Hong Kong",
                    "requests" : 77,
                    "location" : {"lat" : 23.500000, "long" : 114.500000}
                },
                {
                    "identifier" : 406,
                    "name" : "India",
                    "requests" : 244,
                    "location" : {"lat" : 23.041173, "long" : 78.891805}
                },
                {
                    "identifier" : 407,
                    "name" : "Indonesia",
                    "requests" : 80,
                    "location" : {"lat" : -3.187229, "long" : 119.851232}
                },
                {
                    "identifier" : 408,
                    "name" : "Japan",
                    "requests" : 90,
                    "location" : {"lat" : 38.280000, "long" : 140.460000}
                },
                {
                    "identifier" : 403,
                    "name" : "Macau",
                    "requests" : 73,
                    "location" : {"lat" : 22.000000, "long" : 113.000000}
                },
                {
                    "identifier" : 409,
                    "name" : "Malaysia",
                    "requests" : 1,
                    "location" : {"lat" : 3.988639, "long" : 102.064055}
                },
                {
                    "identifier" : 410,
                    "name" : "New Zealand",
                    "requests" : 39,
                    "location" : {"lat" : -45.000000, "long" : 168.000000}
                },
                {
                    "identifier" : 411,
                    "name" : "Philippines",
                    "requests" : 21,
                    "location" : {"lat" : 12.415512, "long" : 123.431038}
                },
                {
                    "identifier" : 412,
                    "name" : "Singapore",
                    "requests" : 112,
                    "location" : {"lat" : 1.356203, "long" : 103.828142}
                },
                {
                    "identifier" : 413,
                    "name" : "South Korea",
                    "requests" : 228,
                    "location" : {"lat" : 36.458351, "long" : 127.855841}
                },
                {
                    "identifier" : 414,
                    "name" : "Sri Lanka",
                    "requests" : 49,
                    "location" : {"lat" : 7.517242, "long" : 80.779494}
                },
                {
                    "identifier" : 415,
                    "name" : "Taiwan",
                    "requests" : 0,
                    "location" : {"lat" : 23.752054, "long" : 120.927318}
                },
                {
                    "identifier" : 416,
                    "name" : "Thailand",
                    "requests" : 222,
                    "location" : {"lat" : 15.660392, "long" : 101.520053}
                },
                {
                    "identifier" : 417,
                    "name" : "Vietnam",
                    "requests" : 214,
                    "location" : {"lat" : 13.318655, "long" : 108.368100}
                },
           ]
          }
        ]

## GLOBAL REQUEST PER TYPE  [/statistic?region=0&group=1]
GLOBAL requests

### Retrieve a GLOBAL request per type [GET]
+ Response 200 (application/json)

        {
            "requests" :
            [
              {
                "type": "Statement Account Name & Address Changes",
                "count": 1203
              },
              {
                "type": "E-Statement Set Up",
                "count": 213
              },
              {
                "type": "eBAM Changes",
                "count": 392
              },
              {
                "type": "CitiDirect Entitlements",
                "count": 12
              },
              {
                "type": "Cash Pooling Set Up",
                "count": 0
              },
              {
                "type": "E Invoice Set Up",
                "count": 123
              },
              {
                "type": "Billing Account Name & Address Change",
                "count": 974
              },
              {
                "type": "Audit Certificates",
                "count": 1500
              },
              {
                "type": "Target Balancing Set Up",
                "count": 783
              },
              {
                "type": "Legal Hierarchy, Address & Name Changes",
                "count": 999
              },
              {
                "type": "Account Opening",
                "count": 111
              },
            ]
        }
 
 
## GLOBAL REQUEST PER TYPE  [/statistic?region=1&group=1]
EMEA requests

### Retrieve a GLOBAL request per type [GET]
+ Response 200 (application/json)
 
        {
            "region" : 1,
            "requests" :
            [
              {
                "type": "Statement Account Name & Address Changes",
                "count": 123
              },
              {
                "type": "E-Statement Set Up",
                "count": 211
              },
              {
                "type": "eBAM Changes",
                "count": 1231
              },
              {
                "type": "CitiDirect Entitlements",
                "count": 0
              },
              {
                "type": "Cash Pooling Set Up",
                "count": 123
              },
              {
                "type": "E Invoice Set Up",
                "count": 311
              },
              {
                "type": "Billing Account Name & Address Change",
                "count": 12
              },
              {
                "type": "Audit Certificates",
                "count": 1
              },
              {
                "type": "Target Balancing Set Up",
                "count": 10
              },
              {
                "type": "Legal Hierarchy, Address & Name Changes",
                "count": 777
              },
              {
                "type": "Account Opening",
                "count": 888
              },
            ]
        }


## GLOBAL REQUEST PER STATE  [/statistic?region=1&group=2]
EMEA requests

### Retrieve a GLOBAL request per type [GET]
+ Response 200 (application/json)
 
        {
            "region" : 1,
            "requests" :
            [
              {
                "type": "New",
                "count": 123
              },
              {
                "type": "Assigned",
                "count": 211
              },
              {
                "type": "In progress",
                "count": 1231
              },
            {
                "type": "Complete",
                "count": 57
              },
            
            ]
        }

## GLOBAL REQUEST PER USER Group  [/statistic?region=1&group=3]
EMEA requests

### Retrieve a GLOBAL request per type [GET]
+ Response 200 (application/json)
 
        {
            "region" : 1,
            "requests" :
            [
              {
                "type": "COE Team",
                "count": 50
              },
              {
                "type": "ASU",
                "count": 211
              },
              {
                "type": "DOC Specialist",
                "count": 1231
              },
              {
                "type": "Country/Hub",
                "count": 0
              },
            ]
        }


## EMEA REQUEST PER TYPE  [/statistic?region=1&group=4]
EMEA requests

### Retrieve a GLOBAL request per type [GET]
+ Response 200 (application/json)
 
        {
            "region" : 1,
            "requests" :
            [
              {
                "year": 2013,
                "month" : 1,
                "count": 150
              },
              {
                "year": 2013,
                "month" : 2,
                "count": 151
              },
              {
                "year": 2013,
                "month" : 3,
                "count": 155
              },
              {
                "year": 2013,
                "month" : 4,
                "count": 180
              },
              {
                "year": 2013,
                "month" : 5,
                "count": 160
              },
              {
                "year": 2013,
                "month" : 6,
                "count": 130
              },
              {
                "year": 2013,
                "month" : 7,
                "count": 110
              },
              {
                "year": 2013,
                "month" : 8,
                "count": 190
              },
              {
                "year": 2013,
                "month" : 9,
                "count": 226
              },
              {
                "year": 2013,
                "month" : 10,
                "count": 230
              },
              {
                "year": 2013,
                "month" : 11,
                "count": 260
              },
              {
                "year": 2013,
                "month" : 12,
                "count": 237
              },
              {
                "year": 2014,
                "month" : 1,
                "count": 170
              },
              {
                "year": 2014,
                "month" : 2,
                "count": 221
              },
              {
                "year": 2014,
                "month" : 3,
                "count": 215
              },
              {
                "year": 2014,
                "month" : 4,
                "count": 255
              },
              {
                "year": 2014,
                "month" : 5,
                "count": 240
              },
              {
                "year": 2014,
                "month" : 6,
                "count": 230
              },
              {
                "year": 2014,
                "month" : 7,
                "count": 220
              },
            ]
        }

## ONBOARD REQUESTS [/requests]
Onboard requests

### Retrieve a onboard requests for dashboard [GET]
+ Response 200 (application/json)

        [
            {
                "requestID" : "RQ000001",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "Sun Life Financial",
                "country" : "Germany",
                "requestState" : "Assigned",
                "requestType" : "InfoRequest",
                "creationDate" : 1407767151,
            },
            {
                "requestID" : "RQ000002",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Xerox",
                "country" : "USA",
                "requestState" : "Submitted",
                "requestType" : "NewClient",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000003",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Xerox",
                "country" : "Netherlands",
                "requestState" : "Completed",
                "requestType" : "ClientSearch",
                "creationDate" : 1407162351,
            },
            {
                "requestID" : "RQ000004",
                "assignee" : "Safronov Roman",
                "clientName" : "AT&T",
                "country" : "Italy",
                "requestState" : "Submitted",
                "requestType" : "NewClient",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000005",
                "assignee" : "Safronov Roman",
                "clientName" : "Nokia",
                "country" : "Italy",
                "requestState" : "Draft",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000006",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "AVON PRODUCTS INCORPORATED",
                "country" : "United Kingdom",
                "requestState" : "Submitted",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407680751,
            },
            {
                "requestID" : "RQ000007",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "AT&T",
                "country" : "Netherlands",
                "requestState" : "Progress",
                "requestType" : "NewFund",
                "creationDate" : 1407767151,
            },
            {
                "requestID" : "RQ000008",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "Arkema",
                "country" : "Portugal",
                "requestState" : "Completed",
                "requestType" : "ExistClient",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000009",
                "assignee" : "Eileen McEnroe",
                "clientName" : "INTERACTIVE BROKERS GROUP INCORPORATED",
                "country" : "USA",
                "requestState" : "Completed",
                "requestType" : "ClientSearch",
                "creationDate" : 1407594351,
            },
            {
                "requestID" : "RQ000010",
                "assignee" : "Safronov Roman",
                "clientName" : "Johnson & Johnson",
                "country" : "Spain",
                "requestState" : "Assigned",
                "requestType" : "NewProduct",
                "creationDate" : 1407680751,
            },
            {
                "requestID" : "RQ000011",
                "assignee" : "Safronov Roman",
                "clientName" : "Sun Life Financial",
                "country" : "Netherlands",
                "requestState" : "Assigned",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407680751,
            },
            {
                "requestID" : "RQ000012",
                "assignee" : "Nancy Desai",
                "clientName" : "Arkema",
                "country" : "Ireland",
                "requestState" : "Submitted",
                "requestType" : "InfoRequest",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000013",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "Sun Life Financial",
                "country" : "Italy",
                "requestState" : "Waiting",
                "requestType" : "DocRequest",
                "creationDate" : 1407421551,
            },
            {
                "requestID" : "RQ000014",
                "assignee" : "Denis Urusov",
                "clientName" : "AVON PRODUCTS INCORPORATED",
                "country" : "Italy",
                "requestState" : "Waiting",
                "requestType" : "NewClient",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000015",
                "assignee" : "Denis Urusov",
                "clientName" : "Johnson & Johnson",
                "country" : "Italy",
                "requestState" : "Assigned",
                "requestType" : "NewClient",
                "creationDate" : 1407248751,
            },
            {
                "requestID" : "RQ000016",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Xerox",
                "country" : "Germany",
                "requestState" : "Waiting",
                "requestType" : "Inflight",
                "creationDate" : 1407421551,
            },
            {
                "requestID" : "RQ000017",
                "assignee" : "Safronov Roman",
                "clientName" : "Nokia",
                "country" : "Denmark",
                "requestState" : "Draft",
                "requestType" : "NewProduct",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000018",
                "assignee" : "Denis Urusov",
                "clientName" : "Johnson & Johnson",
                "country" : "Portugal",
                "requestState" : "Assigned",
                "requestType" : "NewFund",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000019",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Computer Associates",
                "country" : "Germany",
                "requestState" : "Completed",
                "requestType" : "DocRequest",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000020",
                "assignee" : "Nancy Desai",
                "clientName" : "Johnson & Johnson",
                "country" : "Greece",
                "requestState" : "Submitted",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407767151,
            },
            {
                "requestID" : "RQ000021",
                "assignee" : "Eileen McEnroe",
                "clientName" : "AT&T",
                "country" : "Ireland",
                "requestState" : "Waiting",
                "requestType" : "ClientSearch",
                "creationDate" : 1407248751,
            },
            {
                "requestID" : "RQ000022",
                "assignee" : "Denis Urusov",
                "clientName" : "Sun Life Financial",
                "country" : "Norway",
                "requestState" : "Draft",
                "requestType" : "ClientSearch",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000023",
                "assignee" : "Safronov Roman",
                "clientName" : "AT&T",
                "country" : "Belgium",
                "requestState" : "Progress",
                "requestType" : "NewClient",
                "creationDate" : 1407767151,
            },
            {
                "requestID" : "RQ000024",
                "assignee" : "Nancy Desai",
                "clientName" : "AVON PRODUCTS INCORPORATED",
                "country" : "Luxembourg",
                "requestState" : "Progress",
                "requestType" : "DocRequest",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000025",
                "assignee" : "Safronov Roman",
                "clientName" : "AVON PRODUCTS INCORPORATED",
                "country" : "United Kingdom",
                "requestState" : "Submitted",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407421551,
            },
            {
                "requestID" : "RQ000026",
                "assignee" : "Oleksii Matiash",
                "clientName" : "AT&T",
                "country" : "Italy",
                "requestState" : "Progress",
                "requestType" : "NewProduct",
                "creationDate" : 1407680751,
            },
            {
                "requestID" : "RQ000027",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "Johnson & Johnson",
                "country" : "Belgium",
                "requestState" : "Draft",
                "requestType" : "NewClient",
                "creationDate" : 1407421551,
            },
            {
                "requestID" : "RQ000028",
                "assignee" : "Denis Urusov",
                "clientName" : "Xerox",
                "country" : "Austria",
                "requestState" : "Waiting",
                "requestType" : "Inflight",
                "creationDate" : 1407594351,
            },
            {
                "requestID" : "RQ000029",
                "assignee" : "Safronov Roman",
                "clientName" : "Sun Life Financial",
                "country" : "Luxembourg",
                "requestState" : "Draft",
                "requestType" : "ClientSearch",
                "creationDate" : 1407248751,
            },
            {
                "requestID" : "RQ000030",
                "assignee" : "Safronov Roman",
                "clientName" : "Sun Life Financial",
                "country" : "Luxembourg",
                "requestState" : "Progress",
                "requestType" : "ClientSearch",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000031",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "AT&T",
                "country" : "Luxembourg",
                "requestState" : "Progress",
                "requestType" : "ExistClient",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000032",
                "assignee" : "Safronov Roman",
                "clientName" : "INTERACTIVE BROKERS GROUP INCORPORATED",
                "country" : "Sweden",
                "requestState" : "Waiting",
                "requestType" : "DocRequest",
                "creationDate" : 1407248751,
            },
            {
                "requestID" : "RQ000033",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "Computer Associates",
                "country" : "Italy",
                "requestState" : "Assigned",
                "requestType" : "ClientSearch",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000034",
                "assignee" : "Nancy Desai",
                "clientName" : "Computer Associates",
                "country" : "Spain",
                "requestState" : "Submitted",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407421551,
            },
            {
                "requestID" : "RQ000035",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Arkema",
                "country" : "Jersey C.I.",
                "requestState" : "Completed",
                "requestType" : "DocRequest",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000036",
                "assignee" : "Nancy Desai",
                "clientName" : "INTERACTIVE BROKERS GROUP INCORPORATED",
                "country" : "USA",
                "requestState" : "Assigned",
                "requestType" : "SignatureUpdate",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000037",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Sun Life Financial",
                "country" : "Jersey C.I.",
                "requestState" : "Progress",
                "requestType" : "InfoRequest",
                "creationDate" : 1407248751,
            },
            {
                "requestID" : "RQ000038",
                "assignee" : "Denis Urusov",
                "clientName" : "Arkema",
                "country" : "Finland",
                "requestState" : "Submitted",
                "requestType" : "InfoRequest",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000039",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Sun Life Financial",
                "country" : "France",
                "requestState" : "Assigned",
                "requestType" : "DocRequest",
                "creationDate" : 1407594351,
            },
            {
                "requestID" : "RQ000040",
                "assignee" : "Denis Urusov",
                "clientName" : "Nokia",
                "country" : "Belgium",
                "requestState" : "Progress",
                "requestType" : "NewFund",
                "creationDate" : 1407162351,
            },
            {
                "requestID" : "RQ000041",
                "assignee" : "Oleksii Matiash",
                "clientName" : "AT&T",
                "country" : "Finland",
                "requestState" : "Draft",
                "requestType" : "NewClient",
                "creationDate" : 1407767151,
            },
            {
                "requestID" : "RQ000042",
                "assignee" : "Oleksii Matiash",
                "clientName" : "INTERACTIVE BROKERS GROUP INCORPORATED",
                "country" : "Netherlands",
                "requestState" : "Progress",
                "requestType" : "Inflight",
                "creationDate" : 1407248751,
            },
            {
                "requestID" : "RQ000043",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Johnson & Johnson",
                "country" : "Netherlands",
                "requestState" : "Progress",
                "requestType" : "NewClient",
                "creationDate" : 1407853551,
            },
            {
                "requestID" : "RQ000044",
                "assignee" : "Nancy Desai",
                "clientName" : "AT&T",
                "country" : "Germany",
                "requestState" : "Submitted",
                "requestType" : "ExistClient",
                "creationDate" : 1407939951,
            },
            {
                "requestID" : "RQ000045",
                "assignee" : "Jacqueline  Cascardi",
                "clientName" : "INTERACTIVE BROKERS GROUP INCORPORATED",
                "country" : "Norway",
                "requestState" : "Waiting",
                "requestType" : "Inflight",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000046",
                "assignee" : "Nancy Desai",
                "clientName" : "Computer Associates",
                "country" : "Luxembourg",
                "requestState" : "Assigned",
                "requestType" : "DocRequest",
                "creationDate" : 1407335151,
            },
            {
                "requestID" : "RQ000047",
                "assignee" : "Eileen McEnroe",
                "clientName" : "Nokia",
                "country" : "Luxembourg",
                "requestState" : "Draft",
                "requestType" : "ClientSearch",
                "creationDate" : 1407767151,
            },
            {
                "requestID" : "RQ000048",
                "assignee" : "Safronov Roman",
                "clientName" : "Nokia",
                "country" : "United Kingdom",
                "requestState" : "Completed",
                "requestType" : "InfoRequest",
                "creationDate" : 1407507951,
            },
            {
                "requestID" : "RQ000049",
                "assignee" : "Oleksii Matiash",
                "clientName" : "Xerox",
                "country" : "Finland",
                "requestState" : "Submitted",
                "requestType" : "NewProduct",
                "creationDate" : 1407680751,
            },
            {
                "requestID" : "RQ000050",
                "assignee" : "Denis Urusov",
                "clientName" : "Arkema",
                "country" : "Portugal",
                "requestState" : "Assigned",
                "requestType" : "Inflight",
                "creationDate" : 1407421551,
            },
         ]

## ONBOARD REQUEST 1 Details [/requests&requestID=1]
Onboard request details

### Retrieve a onboard requests for dashboard [GET]
+ Response 200 (application/json)

        {
            "initiator" : "Eileen McEnroe",
            "requestSummary" : "Some reuqest summary"
            "managementSummary" : "Some reuqest summary \n management details shoud be there"
        }
        
## ONBOARD REQUEST 2 Details [/requests&requestID=2]
Onboard request details

### Retrieve a onboard requests for dashboard [GET]
+ Response 200 (application/json)

        {
            "initiator" : "Jacqueline  Cascardi",
        }
        
## ONBOARD REQUEST 3 Details [/requests&requestID=3]
Onboard request details

### Retrieve a onboard requests for dashboard [GET]
+ Response 200 (application/json)

        {
            "initiator" : "Oleksii Matiash",
            "comments" :
                [
                    {
                        "author" : " "Mykhailo Vorontsov",
                        "message" : "Hello World!",
                        "date" : 1407767151,
                    },
                    {
                        "author" : "Tetiana Zavialova",
                        "message" : "Hello",
                        "date" : 1407752451,
                    },
                ]
        }        